name: Publish

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
    publish:
        name: Publish Nerdpack
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: NR1 CLI - Install
                run: curl -s https://cli.nr-ext.net/installer.sh | sudo bash

            -   name: NR1 CLI - Add Profile
                run: |
                    echo "Configuring NR1 CLI in ${{ vars.NEW_RELIC_REGION }} region"
                    nr1 profiles:add --name test-env --api-key ${{ secrets.NEW_RELIC_API_KEY }} --region ${{ vars.NEW_RELIC_REGION }}

            -   name: NR1 CLI - Display Version
                run: nr1 --version

            -   name: Publish
                run: npm run publish
                env:
                    NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}

