name: Publish

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        container:
            image: newrelic/cli:v0.97

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Set up Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 22

            -   name: Publish Browser Agent EOL Data
                run: npm publish
                env:
                    NPM_TOKEN: ${{ secrets.NEW_RELIC_API_KEY }}

