name: Publish

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    publish:
        name: Publish Nerdpack
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4
                with:
                    persist-credentials: false

            -   name: NR1 CLI - Install
                run: curl -s https://cli.nr-ext.net/installer.sh | sudo bash

            -   name: NR1 CLI - Add Profile
                run: nr1 profiles:add --name test-env --api-key ${NEW_RELIC_API_KEY} --region ${NEW_RELIC_REGION}
                with:
                    NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
                    NEW_RELIC_REGION: ${{ var.NEW_RELIC_REGION }}

            -   name: NR1 CLI - Display Version
                run: nr1 --version

            -   name: Publish
                run: npm run publish
