name: Publish

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
    publish:
        name: Publish Nerdpack
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Install NR1 CLI
                run: |
                    curl -s https://cli.nr-ext.net/installer.sh | sudo bash
                    nr1 profiles:add --name default --api-key ${{ secrets.NEW_RELIC_API_KEY }} --region ${{ variables.NEW_RELIC_REGION }}

            -   name: NR1 CLI Version
                run: nr1 --version

            -   name: Publish
                run: npm run publish
                env:
                    NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}

