name: Publish

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
    publish:
        name: Publish Nerdpack
        runs-on: ubuntu-latest
        container:
            image: newrelic/cli:v0.97

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Publish
                run: nr1 nerdpack:publish --tag=DEV
                env:
                    NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}

