name: Scrape Browser Agent Data

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape Browser Agent EOL Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install cheerio@1.0.0

      - name: Scrape Browser Agent EOL Data
        run: node gha-scripts/browser-agent/scrape.mjs

      - name: Display Scraped Data
        run: cat browser-agent-eol-policy.json

      - name: Push Scraped Data to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git stash push -- "browser-agent-eol-policy.json"
          git reset --hard
          git clean -fd

          git fetch origin gh-pages
          git checkout gh-pages

          git stash pop
          git add browser-agent-eol-policy.json
          git commit -m "Update browser-agent-eol-policy.json ($(date --iso-8601=seconds))"

          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
